### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by Noc2**
TODO
- [x] Landing Page, update images so that it looks like https://web3.foundation/research/ (but with linking to teched specific projects
- [x] Navbar Links, Wiki, for example, maybe a separate link?

### CODE REVIEW

**Comment by DrW3RK** [comment]
Thank you @Noc2 Let us know when the PR is ready to be reviewed or if any action is needed from our end!

**Comment by Noc2** [comment]
The first draft is ready for review. It's based on this: https://research.web3.foundation/ I recommend maybe taking another look at the links/navbar and potentially adding another initiative on the landing page. 

Screenshot 2023-05-25 at 11 16 28

**Comment by 0xCaso** [comment]
From a design perspective, it's redundant to put the wiki both in "Initiatives" and in the Navbar imo (the Navbar is my local version):

Screenshot 2023-05-25 at 11 45 36

What about changing the section "Initiative" to something like "Overview" and put some links to the website sections (example: "Intro to Blockchain", "Blockchain and Cryptography", "Block Mining and Finality", ...)

Screenshot 2023-05-25 at 11 47 14

**Comment by 0xCaso** [comment]
> The first draft is ready for review. It's based on this: https://research.web3.foundation/ I recommend maybe taking another look at the links/navbar and potentially adding another initiative on the landing page.
> 
> Screenshot 2023-05-25 at 11 16 28

Also, the button "Contribute" links to the GitHub repo. As every page has a "Edit this page" button, should we change it to something like "Read more" and link it to the introduction?

**Comment by Noc2** [comment]
Updated Website by @0xCaso 
Screenshot 2023-05-25 at 12 58 45

Screenshot 2023-05-25 at 12 59 29

**Comment by DrW3RK** [comment]
@0xCaso I like the look of the homepage! If you are free today, would you like to hop on a quick call? The topics currently listed are too granular for the homepage. Would like to have 3-6 cards that provide overview of education initiatives from Web3 Foundation listed there.

**Comment by Noc2** [comment]
@DrW3RK Fyi, see https://github.com/Noc2/w3f-education/pull/2. The tutorial link currently doesn't work until there is a tutorial section.

**Comment by DrW3RK** [comment]
@Noc2 Sure David! We will add content there soon. 

@0xCaso What is with the conflicts with the yarn.lock file? Could you help resolve it? Thank you!

**Review by DrW3RK — APPROVED** [review]

**Comment by CrackTheCode016** [comment]
This could be solved by simply getting rid of the main branches yarn.lock, then using this one's imo.

**Comment by 0xCaso** [comment]
Yea @DrW3RK I think @CrackTheCode016 is right, the easiest thing is to delete the yarn.lock from the main branch and then merge

**Comment by CrackTheCode016** [comment]
This PR has been rebased and rendered conflict-less in #87, so closing this (as it's across forks, not branches).  Thank you guys!

**Pull request closed without merging**
